Updated P3-62 set-up-footer by using map method
petNanny/pn-app pull request #10
Opened 2023-03-01 12:28 UTC by ie0481

using the map method to load the data into each html element

2023-03-04 11:59 UTC, jube33717f requested changes
Everything is good except for one minor issue.

2023-03-04 11:59 UTC, jube33717f commented on package.json
> +}
this change doesn't need

2023-03-04 11:59 UTC, jube33717f commented on src/components/Footer/Footer.tsx
> +};
👍

2023-03-20 15:55 UTC, ShawnWang86b approved these changes

2023-03-21 03:37 UTC, closed without merging