Pn 47 fe set up googlemap
petNanny/pn-app pull request #14
Opened 2023-03-06 02:35 UTC by Johnson-songxq

2023-03-07 12:55 UTC, jube33717f requested changes

2023-03-07 12:55 UTC, jube33717f commented on src/components/GoogleMap/GoogleMap.tsx
> +
This interface can be put under '/src/interfaces'

2023-03-07 12:55 UTC, jube33717f commented on src/components/GoogleMap/GoogleMap.tsx
> +            <img alt="star" src="https://static1.pawshakecdn.com/global/star.svg">
1. svg should be downloaded and put in img folder & imported as a component 
ref: https://blog.logrocket.com/how-to-use-svgs-react/
2. If the score is dynamic, you can control its style dynamically by CSS. In this case, it could be 
```
styledparentDom=styled.div(<{ active: boolean }>)`
    >svg{
        path{
               fill: ${active}?yellow:grey; //styled component can pass parameter
        }
    }
}
`

2023-03-07 12:55 UTC, jube33717f commented on src/components/GoogleMap/GoogleMap.tsx
> +        <MyMapComponent />
this component should be put in another file

2023-03-07 12:55 UTC, jube33717f commented on src/components/GoogleMap/GoogleMap.tsx
> +            <img alt="star" src="https://static1.pawshakecdn.com/global/star.svg">
better to use `map` method

2023-03-07 12:55 UTC, jube33717f commented on src/components/GoogleMap/GoogleMap.tsx
> +const render = (status: Status): React.ReactElement => {
it's actually a component->1. component naming format 2. not name it as render

2023-03-07 12:55 UTC, jube33717f commented on src/components/GoogleMap/GoogleMap.tsx
> +    petSitters.map((item) => {
destructuring: `petSitters.map(({field_address:{latitude,longitude},avatar,name...}))`

2023-03-07 12:55 UTC, jube33717f commented on src/components/GoogleMap/GoogleMap.tsx
> +            <img alt="star" src="https://static1.pawshakecdn.com/global/star.svg">
like line 245

2023-03-07 12:55 UTC, jube33717f commented on src/components/SearchBar/components/AddressInput/AddressInput.tsx
> +      place.formatted_address && changeLocation(place.formatted_address);
better 
```
if(){
}

```
ref: eslint rule-no-unused-expressions

2023-03-10 10:37 UTC, Johnson-songxq commented on src/components/GoogleMap/GoogleMap.tsx
> +    petSitters.map((item) => {
> destructuring: `petSitters.map(({field_address:{latitude,longitude},avatar,name...}))`

done

2023-03-10 13:29 UTC, Johnson-songxq commented on src/components/GoogleMap/GoogleMap.tsx
> +            <img alt="star" src="https://static1.pawshakecdn.com/global/star.svg">
> 1. svg should be downloaded and put in img folder & imported as a component
>    ref: https://blog.logrocket.com/how-to-use-svgs-react/
> 2. If the score is dynamic, you can control its style dynamically by CSS. In this case, it could be
> 
> ```
> styledparentDom=styled.div(<{ active: boolean }>)`
>     >svg{
>         path{
>                fill: ${active}?yellow:grey; //styled component can pass parameter
>         }
>     }
> }
> `
> ```

done

2023-03-11 09:45 UTC, jube33717f approved these changes

2023-03-11 12:07 UTC, merged