Pn 53 sitter gallery
petNanny/pn-app pull request #16
Opened 2023-03-13 10:26 UTC by wowawawoa

What I have done:
1. pet sitter can add photos through pet sitter profile page
![image](https://user-images.githubusercontent.com/75771289/224674490-d3da8d3a-1b7c-43d9-b1a3-7180ab8eb97d.png)
2. pet sitter can resize image when upload 
![image](https://user-images.githubusercontent.com/75771289/224674611-088e75de-0ff3-4926-971a-e9cee08805b6.png)
3. pet sitter can remove image
![image](https://user-images.githubusercontent.com/75771289/224674684-031dddd6-bac3-475c-b4a6-c9eaf98d87e8.png)
4. pet sitter can reorder images 
![image](https://user-images.githubusercontent.com/75771289/224674780-1c714caf-532b-45f4-9126-afb93926edff.png)
5. pet sitter's images can be viewed on pet sitter page
![image](https://user-images.githubusercontent.com/75771289/224675092-6bd9092f-c607-48bc-a7a8-7c672cc041af.png)
6. pet owner can view pet sitter's images with full screen
![image](https://user-images.githubusercontent.com/75771289/224675299-d7de5622-2dae-4853-9d3e-2a522e6ab12c.png)
7. add responsive on pet sitter page
![image](https://user-images.githubusercontent.com/75771289/224675413-5d3a49fa-c176-41ec-8356-dc500d207ec1.png)

2023-03-19 09:19 UTC, jube33717f requested changes
looks good, just some minor things can improve

2023-03-19 09:19 UTC, jube33717f commented on src/components/PetSitterProfile/ProfileGallery/Popup/Popup.tsx
> +
usually, we define variables first, then call hooks, then define functions

2023-03-19 09:19 UTC, jube33717f commented on src/components/PetSitterProfile/ProfileGallery/ProfileImages/ProfileImages.tsx
> +    if (imagesData !== undefined) {
=`if(imagesData)`

2023-03-20 07:51 UTC, wowawawoa commented
update according to the review

2023-03-20 16:00 UTC, ShawnWang86b submitted a review, later dismissed

2023-03-22 00:59 UTC, wowawawoa commented
solved all conversation, updated with dev

2023-03-22 01:08 UTC, jube33717f approved these changes

2023-03-22 01:09 UTC, merged