Pn 44 search panel
petNanny/pn-app pull request #4
Opened 2023-02-22 11:58 UTC by wowawawoa

What I have done:
1. add search panel layout on desktop screen (position fixed) and mobile screen:
![image](https://user-images.githubusercontent.com/75771289/220611766-a0d16ddc-5089-4d02-8872-03b52d9ff86e.png)
![image](https://user-images.githubusercontent.com/75771289/220612047-327416a6-cef4-46b9-85c6-b6e7829c3a70.png)
![image](https://user-images.githubusercontent.com/75771289/220612325-0e2f9bc1-41d3-4174-950c-e94e1541f65f.png)
![image](https://user-images.githubusercontent.com/75771289/220612368-07fdf901-b794-4762-949e-9ff444444b31.png)
2. add google location autocomplete function:
![image](https://user-images.githubusercontent.com/75771289/220612691-d1140d31-36d1-4a31-9fd7-2d8169e039bb.png)
![image](https://user-images.githubusercontent.com/75771289/220612722-aafb333b-6cbc-4c17-ba7b-3a824af35d22.png)
3. add service select function:
![image](https://user-images.githubusercontent.com/75771289/220612967-97456c54-acaa-40e2-bb47-00f649ab89c5.png)
4. add date select function:
![image](https://user-images.githubusercontent.com/75771289/220613058-a5c84a2f-6da7-461c-b0e7-045b9f17e8fb.png)
5. add pet num select function:
![image](https://user-images.githubusercontent.com/75771289/220613146-0adc2458-96f0-4fce-b31d-1d3b58168c46.png)
6. add advanced filter function:
![image](https://user-images.githubusercontent.com/75771289/220613213-304da830-3d63-4030-be7f-addd6f2c26a0.png)
7. add form submit function:
![image](https://user-images.githubusercontent.com/75771289/220613583-e80a1568-34c6-416a-99d0-0bd83be24cd9.png)

2023-02-24 08:55 UTC, jube33717f requested changes

2023-02-24 08:55 UTC, jube33717f commented on src/components/SearchBar/SearchBar.tsx
> +  const [serviceH1, setServiceH1] = useState("Dog Boarding");
better: `serviceHeading`

2023-02-24 08:55 UTC, jube33717f commented on src/components/SearchBar/SearchBar.tsx
> +      console.log(values);
remove line 95

2023-02-24 08:55 UTC, jube33717f commented on src/components/SearchBar/SearchBar.tsx
> +  const [isLaptop] = useMediaQuery("(max-width: 1024px)", { ssr: true, fallback: false });
better to avoid using `useMediaQuery`, it's not compatible with Next.js

2023-02-24 08:55 UTC, jube33717f commented on src/components/SearchBar/SearchBar.tsx
> +    isLaptop ? setIsFilterHide(true) : setIsFilterHide(false);
It should be put in the "render" part

2023-02-24 08:55 UTC, jube33717f commented on src/components/SearchBar/SearchBar.tsx
> +    formik.handleSubmit();
How forms handle the click/submit event:
ref: https://formik.org/docs/overview

2023-02-24 08:55 UTC, jube33717f commented on src/components/SearchBar/SearchBar.tsx
> +  const [isFilterHide, setIsFilterHide] = useState(false);
better `[showFilter, setShowFilter]`

2023-02-24 08:55 UTC, jube33717f commented on src/components/SearchBar/SearchBar.tsx
> +        <InputsContainer display={isFilterHide ? "none" : "flex"}>
`showFilter&&<InputContainer>`

2023-02-24 08:55 UTC, jube33717f commented on src/components/SearchBar/SearchBar.tsx
> +            <StyledMobileBtn onClick={() => setIsFilterHide(false)}>Edit Filters</StyledMobileBtn>
better to have a separate function
`const handleClick=()=>{}`

2023-02-24 08:55 UTC, jube33717f commented on src/components/SearchBar/components/AddressInput/AddressInput.tsx
> +  const [isMobile] = useMediaQuery("(max-width: 1024px)", { ssr: true, fallback: false });
same before

2023-02-24 08:55 UTC, jube33717f commented on src/components/SearchBar/components/AdvancedInput/AdvancedInput.tsx
> +  const [activeItemsCount3, setActiveItemsCount3] = useState(0);
line40-46 Semantics naming

2023-02-24 08:55 UTC, jube33717f commented on src/components/SearchBar/components/AdvancedInput/AdvancedInput.tsx
> +  const handleText1 = () => {
same before

2023-02-24 08:55 UTC, jube33717f commented on src/components/SearchBar/components/AdvancedInput/AdvancedInput.tsx
> +                    name="noChildren"
Semantics naming

2023-02-24 08:55 UTC, jube33717f commented on src/components/SearchBar/components/PetNunInput/PetNumInput.tsx
> +  const list = [
Semantics naming

2023-02-24 08:55 UTC, jube33717f commented on src/components/SearchBar/components/PetNunInput/PetNumInput.tsx
> +                  {props.totalPetsNum > 1 ? (
destructuring:`const PetNumInput = ({totalPetsNum,...}: PetNumInputProps) ` same other places

2023-02-24 08:55 UTC, jube33717f commented on src/components/SearchBar/components/ServiceInput/ServiceInput.tsx
> +  );
normally we don't put code in state

2023-02-24 08:55 UTC, jube33717f commented on src/components/SearchBar/components/ServiceInput/ServiceInput.tsx
> +    );
same before

2023-02-24 08:55 UTC, jube33717f commented on src/setupTests.ts
> +      removeListener: () => {},
()=>void/undefined

2023-02-26 07:17 UTC, jube33717f commented
@ShawnWang86b  can you please follow this up? thx

2023-02-27 13:11 UTC, ShawnWang86b submitted a review, later dismissed

2023-02-28 04:55 UTC, ShawnWang86b approved these changes

2023-02-28 04:57 UTC, merged