Pn 45 user card
petNanny/pn-app pull request #5
Opened 2023-02-24 12:13 UTC by joezheng416

![image](https://user-images.githubusercontent.com/39309708/221175619-b773be32-8b59-4e3a-94f9-6e7f0441df95.png)
Finish the pet sitter list component.
Next step: add responsive and pagination

2023-02-24 13:20 UTC, jube33717f requested changes

2023-02-24 13:20 UTC, jube33717f commented on src/components/userCard/PetSitterCard/PetSitterCard.tsx
> +            <UserAvatar name={prop.name} src={prop.avatar} />
destructuring `const PetSitterCard = ({name,avatar,...}: PetSitter)`
ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

2023-02-24 13:20 UTC, jube33717f commented on src/components/userCard/PetSitterCard/PetSitterCard.tsx
> +        <CardIntroduction>{prop.introduction}</CardIntroduction>
same before

2023-02-24 13:20 UTC, jube33717f commented on src/components/userCard/PetSitterCard/PetSitterCard.tsx
> +              {prop.price} AUD <br></br>/ night{" "}
better to use style to implement

2023-02-24 13:20 UTC, jube33717f commented on src/components/userCard/PetSitterCardList/PetSitterCardList.tsx
> +      ))}
destructuring

2023-03-11 10:46 UTC, ShawnWang86b approved these changes

2023-03-11 11:03 UTC, applestory approved these changes
export const CardHeaderLeft = styled(Flex)`
   &&& {
     gap: 4;
   }
 `;

I am not sure whether the gap:4 should have a unit or not, 4rem or 4px.

2023-03-12 00:00 UTC, joezheng416 commented
> export const CardHeaderLeft = styled(Flex)`&&& { gap: 4; }`;
> 
> I am not sure whether the gap:4 should have a unit or not, 4rem or 4px.

Thanks Dylan. This should be 16px. Updated & committed

2023-03-12 00:02 UTC, joezheng416 commented
> export const CardHeaderLeft = styled(Flex)`&&& { gap: 4; }`;
> 
> I am not sure whether the gap:4 should have a unit or not, 4rem or 4px.

Thanks Dylan. This should be 16px. Updated & committed via 6bbc5c5

2023-03-13 10:44 UTC, merged